name=tr246
version=1.0.0
author=Timo Reinhardt
sentence=Board tr246
paragraph=Diese Library bietet Funktionen für die Ansteuerung des Arduino Nano Board tr246
category=Signal Input/Output
url=https://github.com/TiSpace/tr246
architectures=*